// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7WjUPiWa-M4O2tmwesBNkM9TR1HoG2YM',
    appId: '1:448618578101:web:0b650370bb29e29cce5c93',
    messagingSenderId: '448618578101',
    projectId: 'securefolder-app',
    authDomain: 'securefolder-app.firebaseapp.com',
    storageBucket: 'securefolder-app.appspot.com',
    measurementId: 'G-ZJPZTJCXR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHAsf51D3A407EhQtaVKOcY_PbdJPm9aI',
    appId: '1:448618578101:android:ac3d96667537ce5c93',
    messagingSenderId: '448618578101',
    projectId: 'securefolder-app',
    storageBucket: 'securefolder-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7g23oR2B48AEyDlr_KQXeflKSfVhF8vI',
    appId: '1:448618578101:ios:ac3d96667537ce5c93',
    messagingSenderId: '448618578101',
    projectId: 'securefolder-app',
    storageBucket: 'securefolder-app.appspot.com',
    iosBundleId: 'com.securefolder.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7g23oR2B48AEyDlr_KQXeflKSfVhF8vI',
    appId: '1:448618578101:ios:ac3d96667537ce5c93',
    messagingSenderId: '448618578101',
    projectId: 'securefolder-app',
    storageBucket: 'securefolder-app.appspot.com',
    iosBundleId: 'com.securefolder.app',
  );
}